conda install  _libgcc_mutex
conda install  blas
conda install  brotlipy
conda install  ca-certificates
conda install  certifi
conda install  cffi
conda install  chardet
conda install  cryptography
conda install  cudatoolkit
conda install  decorator
conda install  dgl-cuda11.0
conda install  freetype
conda install  idna
conda install  intel-openmp
conda install  joblib
conda install  jpeg
conda install  jsonpatch
conda install  jsonpointer
conda install  lcms2
conda install  ld_impl_linux-64
conda install  libblas
conda install  libcblas
conda install  libedit
conda install  libffi
conda install  libgcc-ng
conda install  libgfortran-ng
conda install  libgfortran4
conda install  libpng
conda install  libsodium
conda install  libstdcxx-ng
conda install  libtiff
conda install  libuv
conda install  libwebp-base
conda install  lz4-c
conda install  mkl
conda install  mkl-service
conda install  mkl_fft
conda install  mkl_random
conda install  ncurses
conda install  networkx
conda install  ninja
conda install  numpy
conda install  numpy-base
conda install  olefile
conda install  openssl
conda install  pandas
conda install  pillow
conda install  pip
conda install  pycparser
conda install  pyopenssl
conda install  pysocks
conda install  python
conda install  python-dateutil
conda install  python_abi
conda install  pytorch
conda install  pytz
conda install  pyzmq
conda install  readline
conda install  requests
conda install  scikit-learn
conda install  scipy
conda install  setuptools
conda install  six
conda install  sqlite
conda install  threadpoolctl
conda install  tk
conda install  torchaudio
conda install  torchfile
conda install  torchvision
conda install  tornado
conda install  tqdm
conda install  typing_extensions
conda install  urllib3
conda install  visdom
conda install  websocket-client
conda install  wheel
conda install  xz
conda install  zeromq
conda install  zlib
conda install  zstd
conda install  pip:

conda install  bottleneck
conda install  dataclasses
conda install  dill
conda install  future
conda install  munch
conda install  pandarallel
conda install  python-graphviz
conda install  rectorch
conda install  torchviz
